from pydantic import BaseModel
from enum import Enum


# Shared properties
class ProviderType(BaseModel):
    provider_type: str
    services: int
    total_submitted_charge_amount: float


class ProviderTypeEnum(str, Enum):
    allergy_immunology = "Allergy/ Immunology"
    ambulance_service_provider = "Ambulance Service Provider"
    ambulatory_surgical_center = "Ambulatory Surgical Center"
    anesthesiology = "Anesthesiology"
    audiologist = "Audiologist"
    cardiac_surgery = "Cardiac Surgery"
    cardiology = "Cardiology"
    centralized_flu = "Centralized Flu"
    certified_nurse_midwife = "Certified Nurse Midwife"
    certified_registered_nurse_anesthetist_crna = "Certified Registered Nurse Anesthetist (CRNA)"
    chiropractic = "Chiropractic"
    clinical_cardiac_electrophysiology = "Clinical Cardiac Electrophysiology"
    clinical_laboratory = "Clinical Laboratory"
    colorectal_surgery_proctology = "Colorectal Surgery (Proctology)"
    critical_care_intensivists = "Critical Care (Intensivists)"
    dermatology = "Dermatology"
    diagnostic_radiology = "Diagnostic Radiology"
    emergency_medicine = "Emergency Medicine"
    endocrinology = "Endocrinology"
    family_practice = "Family Practice"
    gastroenterology = "Gastroenterology"
    general_practice = "General Practice"
    general_surgery = "General Surgery"
    geriatric_medicine = "Geriatric Medicine"
    gynecological_oncology = "Gynecological Oncology"
    hand_surgery = "Hand Surgery"
    hematology = "Hematology"
    hematology_oncology = "Hematology-Oncology"
    hospice_and_palliative_care = "Hospice and Palliative Care"
    hospitalist = "Hospitalist"
    independent_diagnostic_testing_facility_idtf = "Independent Diagnostic Testing Facility (IDTF)"
    infectious_disease = "Infectious Disease"
    internal_medicine = "Internal Medicine"
    interventional_cardiology = "Interventional Cardiology"
    interventional_pain_management = "Interventional Pain Management"
    interventional_radiology = "Interventional Radiology"
    licensed_clinical_social_worker = "Licensed Clinical Social Worker"
    mass_immunizer_roster_biller = "Mass Immunizer Roster Biller"
    maxillofacial_surgery = "Maxillofacial Surgery"
    medical_oncology = "Medical Oncology"
    nephrology = "Nephrology"
    neurology = "Neurology"
    neurosurgery = "Neurosurgery"
    nuclear_medicine = "Nuclear Medicine"
    nurse_practitioner = "Nurse Practitioner"
    obstetrics_gynecology = "Obstetrics & Gynecology"
    occupational_therapist_in_private_practice = "Occupational Therapist in Private Practice"
    ophthalmology = "Ophthalmology"
    optometry = "Optometry"
    oral_surgery_dentist_only = "Oral Surgery (Dentist only)"
    orthopedic_surgery = "Orthopedic Surgery"
    osteopathic_manipulative_medicine = "Osteopathic Manipulative Medicine"
    otolaryngology = "Otolaryngology"
    pain_management = "Pain Management"
    pathology = "Pathology"
    pediatric_medicine = "Pediatric Medicine"
    peripheral_vascular_disease = "Peripheral Vascular Disease"
    physical_medicine_and_rehabilitation = "Physical Medicine and Rehabilitation"
    physical_therapist_in_private_practice = "Physical Therapist in Private Practice"
    physician_assistant = "Physician Assistant"
    plastic_and_reconstructive_surgery = "Plastic and Reconstructive Surgery"
    podiatry = "Podiatry"
    preventive_medicine = "Preventive Medicine"
    psychiatry = "Psychiatry"
    psychologist_clinical = "Psychologist, Clinical"
    pulmonary_disease = "Pulmonary Disease"
    radiation_oncology = "Radiation Oncology"
    radiation_therapy_center = "Radiation Therapy Center"
    registered_dietitian_or_nutrition_professional = "Registered Dietitian or Nutrition Professional"
    rheumatology = "Rheumatology"
    speech_language_pathologist = "Speech Language Pathologist"
    sports_medicine = "Sports Medicine"
    surgical_oncology = "Surgical Oncology"
    thoracic_surgery = "Thoracic Surgery"
    undefined_physician_type = "Undefined Physician type"
    urology = "Urology"
    vascular_surgery = "Vascular Surgery"

